<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit4a0c88d1bdf63b550831b4f7babd330c
{
    public static $prefixLengthsPsr4 = array (
        'F' => 
        array (
            'Faker\\' => 6,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Faker\\' => 
        array (
            0 => __DIR__ . '/..' . '/fzaninotto/faker/src/Faker',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit4a0c88d1bdf63b550831b4f7babd330c::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit4a0c88d1bdf63b550831b4f7babd330c::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit4a0c88d1bdf63b550831b4f7babd330c::$classMap;

        }, null, ClassLoader::class);
    }
}
